chat phoots
Web-studio-Team3/Frontend-team3 pull request #32
Opened 2023-09-30 15:27 UTC by chewbacca2314

2023-10-01 20:59 UTC, Haskiro requested changes

2023-10-01 20:59 UTC, Haskiro commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.module.scss
> +				content:url(https://i.redd.it/q0ukoq7c39501.jpg);
 картинку нужно ставить через js, она будет динамическая, разная для каждого пользователя

2023-10-01 20:59 UTC, Haskiro commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.tsx
> +	//);
задумка была правильная, почему не закончил?

2023-10-01 20:59 UTC, Haskiro commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.tsx
> +									//src={`http://217.28.220.136:8000/${user_photo}/`}
можно сделать что то типа
`src={message.from_us ? 'http://217.28.220.136:8000/${user_photo}/' : UserImage}`

2023-10-07 16:41 UTC, chewbacca2314 commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.tsx
> +	//);
добавил

2023-10-07 16:42 UTC, chewbacca2314 commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.module.scss
> +				content:url(https://i.redd.it/q0ukoq7c39501.jpg);
изменил

2023-10-07 16:42 UTC, chewbacca2314 commented on src/pages/account/accountSingleChat/components/MessageList/MessageList.tsx
> +									//src={`http://217.28.220.136:8000/${user_photo}/`}
да, это сработало

2023-10-08 17:49 UTC, Haskiro approved these changes

2023-10-08 18:11 UTC, merged